version: 2

sources:
  - name: jaffle_shop
    database: raw  
    schema: dbt_test  
    tables:
      - name: orders
        description: this table contain all order data

      - name: customers
      - name: items
      - name: products
      - name: stores
      - name: supplies 